name: Deploy to Linode VPS  # ✅ This is just the workflow name

on:
  push:
    branches: [ main ]
  workflow_dispatch:         # ✅ Enables manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # or your preferred version

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build the Angular app
      - name: Build Angular app
        run: npm run build

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "HOST=${{ secrets.HOST }}" 
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via rsync
        run: |
          rsync -avz --delete ./dist/ ${{ secrets.USER }}@${{ secrets.HOST }}:/root/deploy/
